# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0002_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric or containany of the following characters: " . _ + - "', regex='^[a-zA-Z0-9._+-]*$')], verbose_name='Username'),
        ),
    ]
