# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question_class', models.CharField(max_length=200)),
                ('question_help', models.CharField(max_length=200)),
                ('question_create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200, unique=True, verbose_name='Category title')),
                ('cat_class', models.CharField(max_length=200, verbose_name='Category class name')),
                ('cat_help', models.CharField(max_length=200, verbose_name='category help')),
                ('cat_create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_deadline', models.DateTimeField()),
                ('question_visibility', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_year', models.IntegerField(default=2017, verbose_name='Semester Year')),
                ('sem_month', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], max_length=50, verbose_name='Semester Month')),
                ('sem_is_active', models.BooleanField(verbose_name='Active')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(related_name='semester', through='management.QuestionSemester', to='management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered_for_semester', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='users',
            field=models.ManyToManyField(related_name='semester', through='management.UserSemester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsemester',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Semester'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to='management.QuestionCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='usersemester',
            unique_together=set([('user', 'semester')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionsemester',
            unique_together=set([('question', 'semester')]),
        ),
    ]
