# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='test', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
