# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_questionsemester_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsemester',
            name='order',
        ),
    ]
