# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_questioncategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_max_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
