# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_question_mark_max_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('mark_datetime', models.DateTimeField(blank=True, null=True)),
                ('click_datetime', models.DateTimeField(auto_now=True)),
                ('question_parameters', models.TextField()),
                ('user_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('question_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.QuestionSemester')),
                ('user_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserSemester')),
            ],
        ),
    ]
