# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20170815_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersemester',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
