# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20170815_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
