# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_semester_sem_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Module'),
        ),
    ]
