# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20170829_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_deadline', models.DateTimeField()),
                ('question_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.QuestionSemester')),
                ('user_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserSemester')),
            ],
        ),
    ]
