# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_userquestionsemester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionsemester',
            unique_together=set([('question_semester', 'user_semester')]),
        ),
    ]
