# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20170905_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionsemester',
            name='question_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.QuestionSemester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquestionsemester',
            name='user_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserSemester'),
            preserve_default=False,
        ),
    ]
