# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20170906_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_help',
            field=models.FileField(upload_to=management.models.Question.user_directory_path),
        ),
    ]
